Repository Vonage/vonage-video-react-app, pull requests merged in 2025-02, with the labels that each got.

#76 VIDCS-3420: Update some language in update screenshots yml file
  .github/workflows/update-screenshots.yml
Labels: update-screenshots

#65 VIDCS-3040: There is a difference in publisher preview on waiting room and the meeting room
  docs/KNOWN_ISSUES.md
  frontend/src/Context/PreviewPublisherProvider/usePreviewPublisher/usePreviewPublisher.tsx
  frontend/src/components/WaitingRoom/VideoContainer/VideoContainer.tsx
  frontend/src/pages/WaitingRoom/WaitingRoom.tsx
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Electron-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Google-Chrome-Fake-Devices-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Microsoft-Edge-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Opera-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-firefox-linux.png
Labels: update-screenshots

#86 VIDCS-3438: Update main branch for VERA 1.0.2
  .github/workflows/auto-update-dependencies.yml
  .github/workflows/deploy-to-vcr.yml
  .github/workflows/run-tests.yml
  .github/workflows/update-screenshots.yml
  .gitignore
  .vcrignore
  README.md
  backend/package.json
  docs/DEPENDENCIES.md
  docs/KNOWN_ISSUES.md
  frontend/package.json
  frontend/src/App.css
  frontend/src/Context/PreviewPublisherProvider/usePreviewPublisher/usePreviewPublisher.tsx
  frontend/src/components/MeetingRoom/SmallViewportHeader/SmallViewportHeader.spec.tsx
  frontend/src/components/MeetingRoom/SmallViewportHeader/SmallViewportHeader.tsx
  frontend/src/components/MeetingRoom/SmallViewportHeader/index.tsx
  frontend/src/components/MeetingRoom/VideoTileCanvas/VideoTileCanvas.tsx
  frontend/src/components/WaitingRoom/VideoContainer/VideoContainer.tsx
  frontend/src/components/WaitingRoom/VideoLoading/VideoLoading.tsx
  frontend/src/pages/MeetingRoom/MeetingRoom.spec.tsx
  frontend/src/pages/MeetingRoom/MeetingRoom.tsx
  frontend/src/pages/WaitingRoom/WaitingRoom.tsx
  integration-tests/package.json
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Electron-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Google-Chrome-Fake-Devices-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Microsoft-Edge-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-Opera-linux.png
  integration-tests/tests/visualComparisons.spec.ts-snapshots/Waiting-page-UI-test-1-firefox-linux.png
  package.json
  sonar-project.properties
  vcr-gha.yml
  vcr.yml.example
  vcrBuild.sh
  yarn.lock
Labels: 👎❌🙅‍♀️ Do not squash merge this PR! 🎃

#89 VIDCS-3441: Add minimum supported width of 360px
  README.md
Labels: skip-ci
